- .gitignore
> feat: gitignore 파일 생성

- hyemin/src/main/java/mission1/Car.java
- hyemin/src/main/java/mission1/CarMain.java
- hyemin/src/main/java/mission1/Company.java
- hyemin/src/main/java/mission1/Employee.java
- hyemin/src/main/java/mission1/EmployeeMain.java
- hyemin/src/main/java/mission1/Student.java
- hyemin/src/main/java/mission1/StudentMain.java
- hyemin/src/main/java/mission1/mission1.md
> #7 
> mission1.md 에 모든 내용이 포함되어 있으며, 자바 클래스는 컴파일 가능하도록 파일 추가해두었습니다.
> [김혜민] 미션 1 제출

- jaehoon/.gitignore
- jaehoon/src/section03/Book.java
- jaehoon/src/section03/BookTest.java
- jaehoon/src/section03/Library.java
- jaehoon/src/section03/MethodChangeTest.java
- jaehoon/미션02.md
> 출제 이슈번호
#8 
자바에서 기본형과 참조형 데이터 타입에 대해 확인하고, 미션 문제를 통해 기본형과 참조형을 메서드의 매개변수로 전달할 때 동작 방식이 어떻게 다른지에 대해 코드로 문제를 풀었어요.
>
- 고급문제의 `Library` 클래스에서 Book을 관리하기 위한 동적 배열을 만들어줬어요.
(ArrayList를 사용하면 좋았겠지만 아직 배우지 않았다는 가정하에 사용하지 않았어요.)
- 아직 mission01이 merger가 되지 않아, 브랜치를 feature단위로 따서 작업후 PR 올립니다.
> [이재훈] 섹션3 미션 제출

- hyemin/src/main/java/mission2/Book.java
- hyemin/src/main/java/mission2/BookMain.java
- hyemin/src/main/java/mission2/BookNotFoundException.java
- hyemin/src/main/java/mission2/Library.java
- hyemin/src/main/java/mission2/TypeMain.java
- hyemin/src/main/java/mission2/mission2.md
> #8 
> 미션 2 제출합니다. (섹션 3)
예외처리를 깔끔하게 할 수 있는 방법을 알고 계신 분은 공유해주시면 감사하겠습니다!
> [김혜민] 미션 2 제출

- jaehoon/src/section04/Book.java
- jaehoon/src/section04/Library.java
- jaehoon/src/section04/LibraryManager1.java
- jaehoon/src/section04/LibraryManager2.java
- jaehoon/src/section04/LibraryManager3.java
- jaehoon/미션03.md
#9 
- 절차지향으로 작성된 코드를 점진적으로 객체지향 코드로 변경했어요.
- `LibraryManager1 -> LibraryManager2 -> LibraryManager3`
- Book과 Library를 속성과 기능을 담은 객체로 만들어 도서 대출 시스템을 구현했어요.
>
- Library 클래스에서 도서를 검색하는 메서드(searchByTitle, searchByIsBn)의 반환값을 Optional로 처리해봤어요.
- Optional은 아직 진도가 아니니, 참고만 해주세요.~
> [이재훈] 섹션4 미션 제출

- hyemin/src/main/java/mission3/Book.java
- hyemin/src/main/java/mission3/Library.java
- hyemin/src/main/java/mission3/LibraryManager.java
- hyemin/src/main/java/mission3/LibraryManager2.java
- hyemin/src/main/java/mission3/LibraryManager3.java
- hyemin/src/main/java/mission3/StringUtils.java
> [김혜민] 미션 3 제출

- seeun/section4/mission1/LibraryManager.java
- seeun/section4/mission2/Book.java
- seeun/section4/mission2/LibraryManager.java
- seeun/section4/mission3/Book.java
- seeun/section4/mission3/Library.java
- seeun/section4/mission3/LibraryManager.java
#섹션
#9 
절차 지향 프로그램을 단계적으로 객체 지향적으로 만들어 보았습니다.
>
도서 대출과 반납 시 부정연산자를 최소화하기 위해서 
if (foundBook.isCheckedOut()) {
throw new IllegalStateException("관련 도서는 대출 중입니다.");
}
와
if (book.isAvailable()) {
throw new IllegalStateException("관련 도서는 대출 중이 아닙니다.");
}
같은 식으로 작성했는데 괜찮은 방법일까요? isCheckedOut은 boolean 타입의 단순 호출함수고 isAvailable메서드는 부정연산자를 쓰고 싶지 않아서 만든 메서드입니다. 아래 같은 경우 도서 반납 시 대출 중이 아닌 도서인지를 판단하는 메서드인데 읽을 때 생각의 흐름이 복잡해질 수 있다고 생각이 들어서요!
늦어서 죄송합니다!!
> feat: section4 미션 제출

- jaehoon/src/section05/Book.java
- jaehoon/src/section05/Library.java
- jaehoon/src/section05/LibraryMain.java
- jaehoon/src/section05/Person.java
- jaehoon/미션04.md
> [이재훈] 섹션5 미션 제출

- chaewon/src/mission4/advanced/Book.java
- chaewon/src/mission4/advanced/Library.java
- chaewon/src/mission4/advanced/LibraryManager.java
- chaewon/src/mission4/easy/EasyMain.java
- chaewon/src/mission4/easy/Person.java
- chaewon/src/mission4/middle/Book.java
- chaewon/src/mission4/middle/MiddleMain.java
#10 
미션 4(섹션 5)에 대한 내용입니다.
프로젝트의 내용 규모는 이전과 유사해서, 코드가 비슷합니다!
생성자 위주로 신경썼기 때문에 퀄리티가 미흡할 수 있습니다. 🙇‍♀️🙇‍♀️
> [조채원] 미션 4 수행

- hyemin/src/main/java/mission4/Book.java
- hyemin/src/main/java/mission4/BookAdvancedMain.java
- hyemin/src/main/java/mission4/BookMain.java
- hyemin/src/main/java/mission4/ErrorCode.java
- hyemin/src/main/java/mission4/Library.java
- hyemin/src/main/java/mission4/LibraryException.java
- hyemin/src/main/java/mission4/Person.java
- hyemin/src/main/java/mission4/PersonMain.java
> [김혜민] 미션 4 제출

- seeun/section5/mission1/Person.java
- seeun/section5/mission1/PersonMain.java
- seeun/section5/mission2/Book.java
- seeun/section5/mission2/BookMain.java
- seeun/section5/mission3/Book.java
- seeun/section5/mission3/Library.java
- seeun/section5/mission3/LibraryManager.java
> feat: section5 미션 제출

- seeun/section6/mission1/패키지의_사용.md
- seeun/section6/mission2/com/example/Main.java
- seeun/section6/mission2/com/example/books/MathHelper.java
- seeun/section6/mission3/com/library/LibraryTest.java
- seeun/section6/mission3/com/library/books/Book.java
- seeun/section6/mission3/com/library/users/User.java
#11 
>
클래스에 정적 팩토리 메서드를 두었을 때 사용 클래스에서 static imort를 해서 사용하는 것에 대해서 어떻게 생각하시나요?
> feat: section6 미션 제출

- jaehoon/src/section07/Account.java
- jaehoon/src/section07/AccountMain.java
- jaehoon/src/section07/User.java
- jaehoon/src/section07/a/AccessControl.java
- jaehoon/src/section07/a/AccessMain1.java
- jaehoon/src/section07/a/Address.java
- jaehoon/src/section07/a/Person.java
- jaehoon/src/section07/a/PersonMain1.java
- jaehoon/src/section07/b/AccessMain2.java
- jaehoon/src/section07/b/PersonMain2.java
- jaehoon/미션06.md
> [이재훈] 섹션 7 미션 제출

- seeun/section7/mission1/AccessTest.java
- seeun/section7/mission2/Address.java
- seeun/section7/mission2/Person.java
- seeun/section7/mission2/PersonAccessTest.java
- seeun/section7/mission2_1/PersonAccessTest.java
- seeun/section7/mission3/Account.java
- seeun/section7/mission3/User.java
- seeun/section7/mission3/UserAccountTest.java
- seeun/section7/mission3/설계.md
> feat: section7 미션 제출

- jaehoon/src/section08/Company.java
- jaehoon/src/section08/ConfigurationMain.java
- jaehoon/src/section08/ConfigurationManager.java
- jaehoon/src/section08/Employee.java
- jaehoon/src/section08/EmployeeMain.java
- jaehoon/미션07.md
#13
`싱글톤 구현에서 아직 Inner클래스나 enum을 배우지 않아, double checked locking 방식을 이용해서 구현했어요.`
>
> [이재훈] 섹션 8 미션 제출

- hyemin/src/main/java/mission7/Company.java
- hyemin/src/main/java/mission7/ConfigurationManager.java
- hyemin/src/main/java/mission7/ConfigurationManagerMain.java
- hyemin/src/main/java/mission7/Employee.java
- hyemin/src/main/java/mission7/EmployeeMain.java
- hyemin/src/main/java/mission7/mission7.md
> [김혜민] 미션 7 제출

- hyemin/src/main/java/mission8/Book.java
- hyemin/src/main/java/mission8/Circle.java
- hyemin/src/main/java/mission8/CircleMain.java
- hyemin/src/main/java/mission8/Library.java
- hyemin/src/main/java/mission8/LibraryMain.java
- hyemin/src/main/java/mission8/Person.java
- hyemin/src/main/java/mission8/PersonMain.java
> [김혜민] 미션 8 제출

- seeun/section9/mission1/Circle.java
- seeun/section9/mission1/CircleTest.java
- seeun/section9/mission2/Person.java
- seeun/section9/mission2/PersonTest.java
- seeun/section9/mission3/Book.java
- seeun/section9/mission3/Library.java
- seeun/section9/mission3/LibraryTest.java
> feat: section9 미션 제출

- hyemin/src/main/java/mission9/Animal.java
- hyemin/src/main/java/mission9/AnimalMain.java
- hyemin/src/main/java/mission9/Book.java
- hyemin/src/main/java/mission9/Car.java
- hyemin/src/main/java/mission9/CarMain.java
- hyemin/src/main/java/mission9/Dog.java
- hyemin/src/main/java/mission9/Ebook.java
- hyemin/src/main/java/mission9/Library.java
- hyemin/src/main/java/mission9/LibraryMain.java
- hyemin/src/main/java/mission9/Vehicle.java
- hyemin/src/main/java/mission9/mission9.md
> #34
> 미션 9 제출합니다.
displayDetails 를 오버라이딩 하는 미션이었지만, toString을 오버라이딩 하는 것이 더 깔끔한 코드인 것 같아 이렇게 구현해보았습니다. 참고 부탁드립니다!
> [김혜민] 미션 9 제출

- chaewon/src/mission9/advanced/AdvancedMain.java
- chaewon/src/mission9/advanced/Book.java
- chaewon/src/mission9/advanced/EBook.java
- chaewon/src/mission9/advanced/Library.java
- chaewon/src/mission9/easy/Animal.java
- chaewon/src/mission9/easy/Dog.java
- chaewon/src/mission9/easy/EasyMain.java
- chaewon/src/mission9/middle/Car.java
- chaewon/src/mission9/middle/MiddleMain.java
- chaewon/src/mission9/middle/Vehicle.java
#38 
미션 9(섹션 10)에 대한 코드 내용입니다.
1. 필드의 final을 언제 붙여야 할지 언제나 고민되네요.
maxSpeed 같은 부분은 판단에 따라 불변성을 줄 수도 있을 것 같은데, 어떻게 생각하시나요? 우선은 final 키워드 없이 다 작성해보았습니다.
2. 고급에 `addBook()` 메서드 이번에는 void로 간단하게 작성해보았습니다! 참고 부탁드립니다. :)
> [조채원] 미션9 수행

- jaehoon/src/section10/advenced/Book.java
- jaehoon/src/section10/advenced/EBook.java
- jaehoon/src/section10/advenced/Library.java
- jaehoon/src/section10/advenced/LibraryMain.java
- jaehoon/src/section10/easy/Animal.java
- jaehoon/src/section10/easy/AnimalMain.java
- jaehoon/src/section10/easy/Dog.java
- jaehoon/src/section10/middle/Car.java
- jaehoon/src/section10/middle/CarMain.java
- jaehoon/src/section10/middle/Vehicle.java
- jaehoon/미션09.md
> [이재훈] 섹션10 미션 제출

- seeun/section10/mission1/Animal.java
- seeun/section10/mission1/AnimalTest.java
- seeun/section10/mission1/Dog.java
- seeun/section10/mission2/Car.java
- seeun/section10/mission2/Vehicle.java
- seeun/section10/mission2/VehicleTest.java
- seeun/section10/mission3/Book.java
- seeun/section10/mission3/BookTest.java
- seeun/section10/mission3/EBook.java
- seeun/section10/mission3/Library.java
> [이세은] section10 미션 제출

- sungbin/section10/.gitignore
- sungbin/section10/src/advance/Book.java
- sungbin/section10/src/advance/EBook.java
- sungbin/section10/src/advance/Library.java
- sungbin/section10/src/advance/Main.java
- sungbin/section10/src/beginner/Animal.java
- sungbin/section10/src/beginner/Dog.java
- sungbin/section10/src/beginner/Main.java
- sungbin/section10/src/middle/Car.java
- sungbin/section10/src/middle/Main.java
- sungbin/section10/src/middle/Vehicle.java
> #38 
> 레벨별 미션 제출
> 전반적인 리뷰 부탁드립니다.
> 섹션10 미션 제출

- jaehoon/src/section11/advenced/Circle.java
- jaehoon/src/section11/advenced/Rectangle.java
- jaehoon/src/section11/advenced/Shape.java
- jaehoon/src/section11/advenced/ShapeMain.java
- jaehoon/src/section11/middle/Animal.java
- jaehoon/src/section11/middle/AnimalMain.java
- jaehoon/src/section11/middle/AnimalShelter.java
- jaehoon/src/section11/middle/Cat.java
- jaehoon/src/section11/middle/Dog.java
- jaehoon/미션10.md
> [이재훈] 섹션11 미션 제출

- hyemin/src/main/java/mission10/Animal.java
- hyemin/src/main/java/mission10/AnimalMain.java
- hyemin/src/main/java/mission10/Cat.java
- hyemin/src/main/java/mission10/Circle.java
- hyemin/src/main/java/mission10/Dog.java
- hyemin/src/main/java/mission10/Rectangle.java
- hyemin/src/main/java/mission10/Shape.java
- hyemin/src/main/java/mission10/ShapeMain.java
- hyemin/src/main/java/mission10/mission10.md
> [김혜민] 미션 10 제출

- chaewon/src/mission10/advanced/AdvancedMain.java
- chaewon/src/mission10/advanced/Circle.java
- chaewon/src/mission10/advanced/Rectangle.java
- chaewon/src/mission10/advanced/Shape.java
- chaewon/src/mission10/easy/Easy.md
- chaewon/src/mission10/middle/Animal.java
- chaewon/src/mission10/middle/Cat.java
- chaewon/src/mission10/middle/Dog.java
- chaewon/src/mission10/middle/MiddleMain.java
> [조채원] 미션 10 수행

- seeun/section11/mission1/다형성.md
- seeun/section11/mission2/Animal.java
- seeun/section11/mission2/AnimalMain.java
- seeun/section11/mission2/Cat.java
- seeun/section11/mission2/Dog.java
- seeun/section11/mission3/Circle.java
- seeun/section11/mission3/Rectangle.java
- seeun/section11/mission3/Shape.java
- seeun/section11/mission3/ShapeMain.java
> feat: section11 미션 제출

- chaewon/src/mission11/advanced/AdvancedMain.java
- chaewon/src/mission11/advanced/Book.java
- chaewon/src/mission11/advanced/EBook.java
- chaewon/src/mission11/advanced/Library.java
- chaewon/src/mission11/advanced/PrintedBook.java
- chaewon/src/mission11/easy/Circle.java
- chaewon/src/mission11/easy/EasyMain.java
- chaewon/src/mission11/easy/Rectangle.java
- chaewon/src/mission11/easy/Shape.java
- chaewon/src/mission11/middle/MediaPlayer.java
- chaewon/src/mission11/middle/MiddleMain.java
- chaewon/src/mission11/middle/Pauseable.java
- chaewon/src/mission11/middle/Playable.java
#45 
미션 11(섹션 12)에 대한 작업 내용입니다.
고급의 getter를 사용하지 않지만, 문제의 요구 사항이기에 작성했습니다.
> [조채원] 미션 11 수행

- hyemin/src/main/java/mission12/AdminUser.java
- hyemin/src/main/java/mission12/AuthService.java
- hyemin/src/main/java/mission12/Book.java
- hyemin/src/main/java/mission12/BookRepository.java
- hyemin/src/main/java/mission12/BorrowingService.java
- hyemin/src/main/java/mission12/Library.java
- hyemin/src/main/java/mission12/LibraryMain.java
- hyemin/src/main/java/mission12/RegularUser.java
- hyemin/src/main/java/mission12/User.java
- hyemin/src/main/java/mission12/UserRepository.java
> #51 
> 미션 12 제출합니다. 
이번 미션은 차후 시간 충분히 있을 때 다시 0부터 구현해봐도 좋을 것 같네요!
> [김혜민] 미션 12 제출
